### ISSUE TITLE
Arrange charts in rows

### ISSUE THREAD

**Issue by chefchansey** [Ditto-money/dashboard#11]
Change the layout on the dashboard to show one chart per row instead of using two columns.

Rationale: Having 2 charts per row looks weird.

<img width="1401" alt="Screen Shot 2021-02-19 at 12 25 35" src="https://user-images.githubusercontent.com/73282620/108461799-fb8a8500-72ad-11eb-9418-5c0487182481.png">

**Comment by brymut** [comment]
Sorry, forgot to push this. Will update asap
