### ISSUE TITLE
Rebase history is not updating

### ISSUE THREAD

**Issue by chefchansey** [Ditto-money/dashboard#15]
The latest rebases are not shown in the [rebase history](https://ditto.money/dashboard/#rebase).

**Comment by chefchansey** [comment]
Re-opening... rebase list has stopped updating on Feb. 24th.

**Comment by developerfred** [comment]
@chefchansey this problem is in the api that is not updating we need to reallocate these issues to the backend ditto

**Api**: https://ditto.money/api

**Comment by developerfred** [comment]
https://graphql.bitquery.io/ide/BhjRLUKybQ#
[Response query](https://gist.github.com/developerfred/7853bd3521bec6e5dd2cc82f8ce31539)

**Comment by venarius** [comment]
Pushed and deployed to production.
