### ISSUE TITLE
Add rebase history page

### ISSUE THREAD

**Issue by chefchansey** [Ditto-money/dashboard#2]
Add a page to the dashboard that tracks the rebase history. For every rebase show the following data:

Date & time
Supply adjustment %
Price before rebase
Price after rebase

**Notes:***

- It should be possible to derive this list from already available data (each supply adjustment in the chart represents a rebase).
- Consider DITTO has vey frequent rebases so pagination is needed.

**Comment by kelonye** [comment]
Implemented & deployed. Will filter out noop rebases later..
