### ISSUE TITLE
Possible regression - dashboard data loading slowly

### ISSUE THREAD

**Issue by chefchansey** [Ditto-money/dashboard#4]
Presumably since the port to React the dashboard loads rather slowly. That is, rebase cooldown and Oracle price show immediately but then it can take up to a minute until the the remaining stats and charts show up.

This feels similar to the slowness in the beginning before walletconnect support was removed. Investigate if this was introduced by one of the latest commits and fix if possible.

**Comment by kelonye** [comment]
Fixed.

**Comment by kelonye** [comment]
Reduced number of chart data sent to frontend. i.e. chart data points are now only around the rebases...
